### ISSUE TITLE
Dynamic shadows

### ISSUE THREAD

**Issue by romfeo** [google-ar/arcore-unreal-sdk#49] opened 2019-01-29 22:50 UTC
I am trying to implement a technique I have seen used in ARkit for UE4 in order to achieve dynamic shadows. With this technique you create an unlit material using the passthrough camera and you appy this material to a plane underneath your camera. Then you enable Cast Modulated Shadows on your scene's Directional Light. 

My problem is that I haven't been able to setup this material in a way that works as it should.

Example 1 (attached). The passthrough material is not aligned and its scaled differently than blank the space, the real world
![example1](https://user-images.githubusercontent.com/2564349/51945809-58e1de00-2428-11e9-85df-aad96214666d.JPG)

Example 2 (attached). With this material setup the alignmed of the shadow plane and the real work is somewhat better, but the shadowing plane does not match in terms of brightness with the real world.
![example2](https://user-images.githubusercontent.com/2564349/51945936-cf7edb80-2428-11e9-9b28-71700060c9a1.JPG)

**Since shadows play a very important role in creating believable experiences, It would be great if you could share a working method to achieve good, dynamic shadows with AR Core.**

My tests are taking place on a Xiaomi Pocophone F1

**Comment by romfeo** [comment] 2019-01-30 07:38
WOW! This is more than an answer than I ever hoped! Thank you so much

**Comment by romfeo** [comment] 2019-01-30 10:54
And a second issue... It seems that I don't have the Get Camera Texture node...

**Comment by romfeo** [comment] 2019-01-30 13:35
Sorry, I've just noticed that the array's elements are on the right of the screen, And that Get Camera Texture is available  google-ar-unreal repo.

**Comment by romfeo** [comment] 2019-01-30 17:01
Your solution worked perfectly. My only issue is that there is a brightness difference...

![screenshot_2019-01-30-18-22-48-621_com yourcompany a1](https://user-images.githubusercontent.com/2564349/51998357-2a641180-24c1-11e9-9ab5-b0673d8dfcf9.png)

I have mobile hdr enabled. If i disable it, the color difference is not present, but neither are the shadows.

I've ended up adding a SQRT node in my material, just after the Texture Sample, and it seems to correct the problem, but I am not sure if this is the correct approach.

**Comment by bopangzz** [comment] 2019-01-30 17:15
Are you using gles3 or gles2? There is a issue in color space when using
gles3, which will be fixed in our next release. You workaround should be
fine for now.

**Comment by romfeo** [comment] 2019-01-30 23:21
Hmm, i am not on gles3. I have it disabled. I am using gles2 and still have the issue. My workaround is not perfect either, as there is still some difference in the brightness, depending on the lighting conditions

**Comment by wickerman123** [comment] 2019-01-31 01:18
Thank you so much for sharing this!

What's the purpose of the Passthrough camera node in the material editor? Everywhere I look people are tying to use it like Romfeo has here (myself included) and hit the same issues.

Also is there any solution for doing this in the binary version of Unreal? It's not a big issue if there's not - though it's annoying that support for ARCore is very slow in Unreal and it's still using an old version.

**Comment by romfeo** [comment] 2019-01-31 12:55
Thank you so much for taking so much to help us! So the million dollar question is... When can we expect the next release? :)

**Comment by wickerman123** [comment] 2019-01-31 20:11
Really appreciate the help.

I just tried adding the files to a binary UE4 4.21 project and got met with the following message:

"The following modules are missing or built with a different engine version:

- GoogleARCoreBase
-GoogleARCoreRendering"

Upon rebuilding the project fails to compile.

I'd have thought the most up to date version wouldn't have any issues rebuilding the plugin. Do you have any advice? I'm really keen to be able to use the latest version of ARCore in existing projects.

**Comment by bopangzz** [comment] 2019-01-31 20:19
The newer version of GoogleARCore plugin might rely on some engine source code changes, which might not be in the binary version of UE 4.21. I really recommend you to use the source code version of Unreal Engine if you want to use the latest ARCore plugin. 

Is there any feature you want in particular in the newer version? If you only need the UGoogleARCoreFrameFunctionLibrary::GetCameraTexture() function with the binary version of Unreal, yo u best bet would be use the source code of the GoogleARCore plugin in here: https://github.com/EpicGames/UnrealEngine/tree/release/Engine/Plugins/Runtime/GoogleARCore
And add the function yourself in that version.

**Comment by bopangzz** [comment] 2019-02-04 23:01
It is probably too complicated if you have no experience with programming. Can you start with using that GoogleARCorePassthroughCamera first and see if you see any issues? If you find the camera texture is not in sync, an easier way to fix it is to change the GoogleARCorePassthrough material to also use that node instead.

**Comment by wickerman123** [comment] 2019-02-05 00:57
> 
> 
> It is probably too complicated if you have no experience with programming. Can you start with using that GoogleARCorePassthroughCamera first and see if you see any issues? If you find the camera texture is not in sync, an easier way to fix it is to change the GoogleARCorePassthrough material to also use that node instead.

Hi, you can see in this image what I had to do to get the passthrough camera to _somewhat_ work in the binary release of UE4: https://i.imgur.com/7TCMFMa.png
The resulting effect can be seen in this video: https://www.youtube.com/watch?v=CwJFGYMb0mY

There's a noticeable switch when that passthrough material starts getting drawn. I tried adjusting the scale values to account for aspect ratio and adjusting the gamma (0.45045 rather than 0.22) but to no avail. Also once you see the incorrect aspect ratio it's hard to unsee it.

The result in this GitHub build works a lot better - if a bit trickier to setup and _seemingly_ more expensive - creating a dynamic instance of the PP material and applying it as a blendable to the possessed camera and updating it on tick: https://i.imgur.com/6r41qUP.png https://i.imgur.com/PIQ26GI.png

From what I've seen of ARKit tutorials, it's setup is similar to how we incorrectly assumed the "GoogleARCoreCameraPassthrough" node worked. Is there any plans to make this process simpler or is there a reason I'm overlooking that justifies the method you shared with us?

Again, thank you very much for all the help!

**Comment by wickerman123** [comment] 2019-02-05 01:07
Oh and in regards to the Mobile HDR issue in the current built, I was trying to apply gamma correction like I had before and wasn't able to reach a result, until I added in this node network: https://i.imgur.com/h8njAjJ.png   -  at which point seemed to flip a switch that made my gamma correction start working as desired - even after deleting all the levels nodes and connecting the texture sample output straight to the power node. See the result here: https://i.imgur.com/BzARPlf.jpg

The left of this image is what the camera texture looked like (with gamma adjustment) before that "switch" that happened: https://i.imgur.com/lBpxZiv.jpg

**Comment by wickerman123** [comment] 2019-02-05 01:38
My first example is in the binary release of UE4 4.20 so there's no way for me to get the camera texture UVs - as per our previous discussion. Correct me if I'm wrong here.

Passing the UVs into the GoogleARCoreCameraPassthrough does work however the corrections you mentioned do not produce ideal results. On the left of this image is the output run though the power node with an exponent of 2 and the right is the output run through the sqrt node: https://i.imgur.com/MtNhlLF.jpg

I'm aware that passthrough materials don't need to be done in a post process but the effect I'm producing does require it to be done in the post process - as I don't know how to write custom shaders at an engine level and thus tell shader fragments only to render when the stencil buffer is at a value of 1. The "magic door" effect is commonly produced in Unity but due to the limitations I just mentioned, the only workaround I've thought up is to use the stencil buffer as a mask in a passthrough camera overlay.

**Comment by bopangzz** [comment] 2019-02-05 01:44
You can still calculate the correct uv using the node GetPassthroughCameraImageUV and pass in the result uv in the material to modify the screen space uv to sample the GoogleARCoreCameraPassthrough node correctly.

As for the gamma issue, what is the texture looks like if you don't do any modification after sampling the GoogleARCoreCameraPassthrough node? If it looks correct, you don't need to do anything there.

**Comment by wickerman123** [comment] 2019-02-05 01:49
> 
> 
> You can still calculate the correct uv using the node GetPassthroughCameraImageUV and pass in the result uv in the material to modify the screen space uv to sample the GoogleARCoreCameraPassthrough node correctly.
> 
> As for the gamma issue, what is the texture looks like if you don't do any modification after sampling the GoogleARCoreCameraPassthrough node? If it looks correct, you don't need to do anything there.

Ah yes of course - sorry it's 1:45am for me so I'm running on empty!

Without the 0.22 correction the output looks like this: https://i.imgur.com/6FP4zHT.jpg

Though this only happens with "Mobile HDR" enabled - which has to be enabled for this post process material to work. When I had "Mobile HDR" disabled, the post process material would simply not get applied to the camera.

**Comment by zyadmardini** [comment] 2019-02-05 09:05
thanks for your help guys , been going on with this for days now , but i still can find the "get camera texture node" working with 4.21 with and the latest sdk (using arcore's helloAR template)

**Comment by romfeo** [comment] 2019-02-25 14:59
Hi there,

Just wanted to let you know that I have update to the new release and the  issue in color space when using gles3 or gles2 still remains...

**Comment by bopangzz** [comment] 2019-02-25 18:03
Hi romfeo,

Can you attach a screen shot explain the problem you are seeing in the new release?

**Comment by romfeo** [comment] 2019-03-03 16:06
> Hi romfeo,
> 
> Can you attach a screen shot explain the problem you are seeing in the new release?

Hello again,

Do you notice the color difference on the carpet? The darker part is where I have applied the material you have shared in this thread as a reply to my initial question

**Comment by Thoeme77** [comment] 2019-03-04 18:54
Many many thanks to "bopangzz" for the solution and the many in-depth answers!

**You made my day!**

Luckily enough I don't have the coloring/gamma issues mentioned here by "romfeo". I've used the custom built version (4.20 with AR Core 1.6) generated by you guys . 

The 4.21 version with AR Core 1.7 didn't work for me. On both testing phones the screen stayed black after launching the app.

**Comment by bopangzz** [comment] 2019-03-04 20:19
> > Hi romfeo,
> > Can you attach a screen shot explain the problem you are seeing in the new release?
> 
> Hello again,
> 
> Do you notice the color difference on the carpet? The darker part is where I have applied the material you have shared in this thread as a reply to my initial question
> ![screenshot_2019-03-03-16-46-10-588_com yourcompany a1](https://user-images.githubusercontent.com/2564349/53697934-0c9b0c80-3ddf-11e9-839d-0d3f38429689.png)

**Comment by bopangzz** [comment] 2019-03-04 20:22
> > Hi romfeo,
> > Can you attach a screen shot explain the problem you are seeing in the new release?
> 
> Hello again,
> 
> Do you notice the color difference on the carpet? The darker part is where I have applied the material you have shared in this thread as a reply to my initial question
> ![screenshot_2019-03-03-16-46-10-588_com yourcompany a1](https://user-images.githubusercontent.com/2564349/53697934-0c9b0c80-3ddf-11e9-839d-0d3f38429689.png)

Hi romfeo,

I did the test again and I can't reproduce the issue you are having. Can you try use the ARCoreOcclusionMaterial shipped with Unreal ARCore 1.7 release, you should be able to find that material under GoogleARCore Content in the content browser. If you don't see the folder, make sure you enable "Show Engine Content" and "Show Plugin Content" int the view options.

**Comment by bopangzz** [comment] 2019-03-04 20:23
> Many many thanks to "bopangzz" for the solution and the many in-depth answers!
> 
> **You made my day!**
> 
> Luckily enough I don't have the coloring/gamma issues mentioned here by "romfeo". I've used the custom built version (4.20 with AR Core 1.6) generated by you guys .
> 
> The 4.21 version with AR Core 1.7 didn't work for me. On both testing phones the screen stayed black after launching the app.

Can you create a new issue for the black screen issue you saw when using 1.7 release? Can you please attach an Android logcat when the issue happens. Thank you!

**Comment by romfeo** [comment] 2019-03-05 13:13
After I've looked in the included occlusion material in the new version of the plugin, I've realized that I was missing the 127grey texture from my material. I was using a different texture. Everything works great now!
Thanks for everything

**Closed** 2019-03-05 18:56 UTC

**Comment by Thoeme77** [comment] 2019-03-07 17:23
> > Many many thanks to "bopangzz" for the solution and the many in-depth answers!
> > **You made my day!**
> > Luckily enough I don't have the coloring/gamma issues mentioned here by "romfeo". I've used the custom built version (4.20 with AR Core 1.6) generated by you guys .
> > The 4.21 version with AR Core 1.7 didn't work for me. On both testing phones the screen stayed black after launching the app.
> 
> Can you create a new issue for the black screen issue you saw when using 1.7 release? Can you please attach an Android logcat when the issue happens. Thank you!

Sure, I'll do that next week.

But I have another question which came up today.

The solution works perfectly fine on Android. But on the iPad Pro (iOS 12.1.1) the texture didn't get updated and stayed green (in my case the default texture). Do you have any clue why that could be the case? Is there a specific reason why this wouldn't work on iOS?

**Comment by bopangzz** [comment] 2019-03-07 17:27
That texture node only work on Android. On iOS with ARKit you will need to use the node provided by ARKit. You can check how the passthrough camera material in ARKit plug uses the node to render the background image. It should be in the content folder in your ARKit Plugin.

**Comment by Thoeme77** [comment] 2019-03-07 17:28
> That texture node only work on Android. On iOS with ARKit you will need to use the node provided by ARKit. You can check how the passthrough camera material in ARKit plug uses the node to render the background image. It should be in the content folder in your ARKit Plugin.

Okay, many thanks than I will try that.
To bad until that point everything was cross-platform compatible.

**Comment by Thoeme77** [comment] 2019-03-12 23:31
> That texture node only work on Android. On iOS with ARKit you will need to use the node provided by ARKit. You can check how the passthrough camera material in ARKit plug uses the node to render the background image. It should be in the content folder in your ARKit Plugin.

You're the best!
That worked as well. In my case to get the right gamma correction, I had to plug in the "YUV_to_sRGBCustom" node directly, without using the other two. I've tested this with an iPad Pro 12.9''. I wasn't able to test this with an iPhone so far.

**Comment by Thoeme77** [comment] 2019-03-15 16:05
Quick question: Is it possible to use this setup for AR Core with a Post Process Material as well? I wanted to use this for a terrain mesh, but there it stopped working.

**Comment by bopangzz** [comment] 2019-03-15 19:34
> Quick question: Is it possible to use this setup for AR Core with a Post Process Material as well? I wanted to use this for a terrain mesh, but there it stopped working.

You mean sampling the camera texture in a Post process material? You should be able to do that kind of things. What issues you are getting?

**Comment by Thoeme77** [comment] 2019-03-16 00:42
> > Quick question: Is it possible to use this setup for AR Core with a Post Process Material as well? I wanted to use this for a terrain mesh, but there it stopped working.
> 
> You mean sampling the camera texture in a Post process material? You should be able to do that kind of things. What issues you are getting?

Hi, 

never mind the issues, I was just dumb. I was using the same Material Parameter Collection for two different Actors which didn't work. But I changed the setup to Vector Parameter Values which are getting instanced. 

And yes exactly. I did that with the ARKit solution, but there I had no issues with the "passthrough" node (only gamma correction, which I was able to fix). See attached image for AR Kit material.

![ARKit_Occlusion_Setup](https://user-images.githubusercontent.com/12977782/54468408-94dcc280-478c-11e9-9a85-f9af158da2f5.JPG)

**Comment by MrPositivity** [comment] 2019-06-21 07:26
Good Day, Im On UE4 4.22.2 and I tried all of the thees solutions mentioned in this post but they are not working for Android, When applying material and function to update the material , the shadow plane under object just looks with different aspect ratio, or feels out of place and you can clearly see where that shadow plane is. 
Can anyone provide a straight forward example for this? also Included material in Engine Content is not like one in Screenshot. 

Aivis

**Comment by NDmitriy98** [comment] 2020-10-16 10:54
I think it can help you:
https://answers.unrealengine.com/questions/988932/render-in-main-pass-ar-android.html
