### ISSUE TITLE
Handheld AR 4.19 template crashes on S8 with ARCore 1.0

### ISSUE THREAD

**Issue by alllesss** [google-ar/arcore-unreal-sdk#12] opened 2018-03-16 07:31 UTC
Hi,
After the full release of 4.19 I tried to :
1- Created a "Handheld AR" Template
2- Configured Android SDK in project settings (Accepted SDK, Min/Target SDK is 19)
2- Built it for Android ASTC 
3- Got crash on start with my S8 (ARCore 1.0)

**Comment by bopangzz** [comment] 2018-03-16 07:33
Can you attach the logcat when you got the crash?

**Comment by alllesss** [comment] 2018-03-16 08:21
[Crash Report.txt](https://github.com/google-ar/arcore-unreal-sdk/files/1818428/Crash.Report.txt)

**Comment by bopangzz** [comment] 2018-03-16 19:28
Did you see the app asked for External Read/Write permission the first time you launch the app? If not, can you try change your Target SDK to 24 and rebuild the app?

From the logcat, it looks like you app crashes because it couldn't load the Internationalization file, which is very likely caused by lack of Android External Read Permission on you app. 

Though you shouldn't need to request runtime read permission if your Min/Target SDK is 19, but my guess is since you build with ARCore support, and the ARCore library is targeting Android 24 which make you app target 24 as well.

And after you set Target SDK to 24 in Unreal, it should request External Read/Write permission when the app started.

**Comment by alllesss** [comment] 2018-03-17 09:43
@bopangzz I've never got Read/Write permissions. however, I checked the app's permissions defaults and read/write is already enabled.

Tried SDK 24 still crashes. with no permission being asked.
So the crash is, it loads Unreal Splash screen for a sec and then closes the app.

**Comment by bopangzz** [comment] 2018-03-17 23:26
Hmm, then it isn't the permission problem. This is the crash callstack from your log:
03-16 11:43:20.115 16961 16961 F DEBUG   :     #00 pc 020c35d4  /data/app/com.ARtest-1/lib/arm/libUE4.so (_Z9vswprintfPwiPKwSt9__va_list+1324)
03-16 11:43:20.116 16961 16961 F DEBUG   :     #01 pc 022457a4  /data/app/com.ARtest-1/lib/arm/libUE4.so (_ZN4FMsg17Logf_InternalImplEPKciRK5FNameN13ELogVerbosity4TypeEPKwz+796)
03-16 11:43:20.116 16961 16961 F DEBUG   :     #02 pc 021a55e0  /data/app/com.ARtest-1/lib/arm/libUE4.so (_ZN24FICUInternationalization18InitializeTimeZoneEv+300)
03-16 11:43:20.116 16961 16961 F DEBUG   :     #03 pc 021a34a0  /data/app/com.ARtest-1/lib/arm/libUE4.so (_ZN24FICUInternationalization10InitializeEv+2752)
03-16 11:43:20.116 16961 16961 F DEBUG   :     #04 pc 0219aa54  /data/app/com.ARtest-1/lib/arm/libUE4.so (_ZN21FInternationalization3GetEv+164)
03-16 11:43:20.116 16961 16961 F DEBUG   :     #05 pc 0223a538  /data/app/com.ARtest-1/lib/arm/libUE4.so (_Z25BeginInitTextLocalizationv+12)
03-16 11:43:20.116 16961 16961 F DEBUG   :     #06 pc 0209feb8  /data/app/com.ARtest-1/lib/arm/libUE4.so (_ZN11FEngineLoop7AppInitEv+68)
03-16 11:43:20.116 16961 16961 F DEBUG   :     #07 pc 0209b040  /data/app/com.ARtest-1/lib/arm/libUE4.so (_ZN11FEngineLoop7PreInitEPKw+8880)
03-16 11:43:20.116 16961 16961 F DEBUG   :     #08 pc 0208a4c8  /data/app/com.ARtest-1/lib/arm/libUE4.so (_ZN11FEngineLoop7PreInitEiPPwPKw+3928)
03-16 11:43:20.117 16961 16961 F DEBUG   :     #09 pc 02088ea4  /data/app/com.ARtest-1/lib/arm/libUE4.so (_Z11AndroidMainP11android_app+2780)
03-16 11:43:20.117 16961 16961 F DEBUG   :     #10 pc 02095d48  /data/app/com.ARtest-1/lib/arm/libUE4.so (android_main+204)
03-16 11:43:20.117 16961 16961 F DEBUG   :     #11 pc 020b55d8  /data/app/com.ARtest-1/lib/arm/libUE4.so
03-16 11:43:20.117 16961 16961 F DEBUG   :     #12 pc 00047a63  /system/lib/libc.so (_ZL15__pthread_startPv+22)
03-16 11:43:20.117 16961 16961 F DEBUG   :     #13 pc 00019e65  /system/lib/libc.so (__start_thread+6)

It looks like a general UE4 crash and it is not related ARCore. I assume you packaged the project and install it on your phone using the install script? Can you try check the "Package game data inside APK" checkbox in Project Settings->Android and repackage the game? Another thing to try is start your game using the Unreal launch button.

**Comment by alllesss** [comment] 2018-03-19 11:08
I tried installing the APK and lunch. with both methods I got crash. also checked it in my friend's S7 and still crashed.
So you're right this should be the problem of UE4's build. I saw another person ran into the same problem in UE4's answerhub. If it expands then we should hear back from Epic I guess.

**Comment by bopangzz** [comment] 2018-03-19 18:30
Have you tried the "Package game data inside .apk" option?

**Comment by alllesss** [comment] 2018-03-20 09:46
My time zone is set to Tehran UTC+03:30

**Comment by freelife0417** [comment] 2018-03-26 03:54
I went through the same steps as the AR template in version 4.19.0 with the Galaxy S7 device.

The same problem (crash) occurred.
 
I saw the log and I do not know what the problem is.
Attach an Unreal log file and an Android logcat file.

Previously, I checked with the HelloARUnreal Sample Project on the Galaxy s7 in the steps below
I am not sure that the AR plugin currently installed in Unreal 4.19.0 works properly with S7, so please check here.

https://developers.google.com/ar/develop/unreal/quickstart

**Comment by bopangzz** [comment] 2018-03-26 04:10
@freelife0417 Your crash is a different problem. It looks like you are using Vulkan instead of open gles in your build? ARCore doesn't support Vulkan yet. Can you try build without vulkan enabled?

**Comment by freelife0417** [comment] 2018-03-26 05:31
@bopangzz 
I solved the problem with your answer.
Thank you.

Personally I'm curious, Could you tell me where you saw the vulcan api error message in the log?

**Comment by bopangzz** [comment] 2018-03-26 18:20
@freelife0417 I don't see vulcan api error message bug. I just saw logs from VulkanRHI which indicates it is using Vulkan.

**Comment by alllesss** [comment] 2018-03-28 16:53
@bopangzz some1 in ue4's forum [mentioned](https://forums.unrealengine.com/development-discussion/vr-ar-development/1446094-ar-template-not-working-on-galaxy-s7-arcore) that the crash doesn't occur with Android 7. can you confirm it's related to android version and ARcore doesn't support Android 8 ?!
If so, it's pretty weird though

**Comment by bopangzz** [comment] 2018-03-28 18:13
@alllesss ARCore should works fine with Android 7. I don't think that timezone related crash has anything to do with ARCore. Have you tried build the ThirdPerson template on Android, which doesn't have ARCore plugin enabled?

**Comment by bopangzz** [comment] 2018-03-29 00:33
@alllesss I can reproduce your issue now on a S8. So it looks like a pure Unreal issue, basically if you set your timezone on your phone with something like xx:30, you will get the crash. 
I haven't got a chance to try it but If you can also reproduce the crash with a general Unreal Android app, like the ThirdPerson template, you should fill a bug to Epic and let them fix on their side.

**Comment by alllesss** [comment] 2018-03-29 09:24
@bopangzz oh wow! was exactly that ... I tried xx:00 time zones and it worked. will file a bug to Epic. Thanks!

**Comment by bopangzz** [comment] 2018-04-10 18:29
The crash that related to timezone should be fixed in Unreal 4.19.1. If you are using Epic's Unreal Engine releases, you should have the fix after upgrading to 4.19.1. If you are using the forked GoogleAR Unreal Engine repo, it will be updated to 4.19.1 in our next release.

**Closed by bopangzz** 2018-04-10 18:29 UTC
Labels: Unreal bug

**Comment by hanson1985** [comment] 2019-03-03 23:31
Hi i have problem with UE 4.21.2 on samsung galaxy 8 app is closing on phone

**Comment by jiomex** [comment] 2019-03-22 12:33
The same on my Note 9

**Comment by bopangzz** [comment] 2019-03-22 17:16
@hanson1985 @jiomex Please capture a Android logcat of the crash and I can help take a look.

**Comment by jiomex** [comment] 2019-03-24 18:00
the same on my note 8, with latest Android 9
